# Generated by Django 4.2.7 on 2023-11-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_followers_alter_user_username_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
