# Generated by Django 4.2.7 on 2023-11-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follow_from', 'follow_to')},
        ),
    ]
