# Generated by Django 4.2.7 on 2023-11-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
