services:
  drfpostgres:
    image: postgres
    container_name: drfpostgres
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drf_socialnet_db
    volumes:
      - drf-db-volume:/var/lib/postgresql/data
    restart: always  

  drfsocialmyapp:
    build: .
    container_name: drfsocialmyapp
    networks:
      - mynetwork
    environment:
      DATABASE_NAME: drf_socialnet_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: drfpostgres  
      USING_DATABASE: postgresql
    command: >
          sh -c "python manage.py makemigrations &&
                 python manage.py migrate
                 python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - drfpostgres 
    ports:
          - 8000:8000
    restart: always 

networks:
  mynetwork:
    driver: bridge 

volumes:
  drf-db-volume: 
